@echo off
setlocal ENABLEDELAYEDEXPANSION

set ROOT=%~dp0
set ASSETS=%ROOT%assets
set TMP=%ROOT%_downloads

echo [TEOREM] Preparing asset folders...
if not exist "%ASSETS%" mkdir "%ASSETS%"
if not exist "%ASSETS%\sprites" mkdir "%ASSETS%\sprites"
if not exist "%ASSETS%\music" mkdir "%ASSETS%\music"
if not exist "%ASSETS%\sfx" mkdir "%ASSETS%\sfx"
if not exist "%ASSETS%\fonts" mkdir "%ASSETS%\fonts"
if not exist "%ASSETS%\backgrounds" mkdir "%ASSETS%\backgrounds"
if not exist "%TMP%" mkdir "%TMP%"

set MANIFEST=%ROOT%assets_manifest.txt
(
	echo # Asset manifest for TEOREM – OPTIMUM REJİM
	echo # Generated by download_assets.bat
) > "%MANIFEST%"

call :download_and_unzip "https://kenney.nl/media/pages/assets/tiny-dungeon/04d9d4e2f1-1677514960/tiny-dungeon.zip" "%TMP%\tiny-dungeon.zip" "%ASSETS%\sprites" "Kenney Tiny Dungeon"
call :download_and_unzip "https://kenney.nl/media/pages/assets/rpg-audio/9d19a56af7-1677514859/rpg-audio.zip" "%TMP%\rpg-audio.zip" "%ASSETS%\sfx" "Kenney RPG Audio"
call :download_and_unzip "https://kenney.nl/media/pages/assets/space-backgrounds/4c74f2f02f-1677514822/space-backgrounds.zip" "%TMP%\space-backgrounds.zip" "%ASSETS%\backgrounds" "Kenney Space Backgrounds"

if exist "%TMP%" rmdir /s /q "%TMP%"

echo [TEOREM] Done. If any downloads failed, the game will use placeholder shapes.
exit /b 0

:download_and_unzip
set URL=%~1
set ZIP=%~2
set DEST=%~3
set NAME=%~4

echo [TEOREM] Downloading %NAME%...
powershell -Command "try { Invoke-WebRequest -Uri '%URL%' -OutFile '%ZIP%' -UseBasicParsing } catch { exit 1 }"
if errorlevel 1 (
	echo [WARN] Failed to download %NAME%. Using placeholders.
	echo %NAME% - FAILED >> "%MANIFEST%"
	exit /b 0
)

echo [TEOREM] Extracting %NAME%...
powershell -Command "try { Expand-Archive -Path '%ZIP%' -DestinationPath '%DEST%' -Force } catch { exit 1 }"
if errorlevel 1 (
	echo [WARN] Failed to extract %NAME%. Using placeholders.
	echo %NAME% - DOWNLOAD OK, UNZIP FAILED >> "%MANIFEST%"
	exit /b 0
)

echo %NAME% - OK >> "%MANIFEST%"
exit /b 0
